#!/bin/bash -e

#
# Remove (deregister) old Flatcar AMIs from AWS account, and/or delete EBS
# snapshots.
#
# Requires a valid flatcar-linux aws API key + secret (e.g. jenkins')
#

AWS_REMOVE_OLDER_THAN="1 year ago" # this is a date(1) --date string

function print_aws() {
    # for --dry-run
    echo "aws $*"
}
# --

function aws_list_amis() {
    local profile="$1"

    # We're not using --profile here since Jenkins does not have
    # "describe-regions" access rights
    local regions=""
    regions=$(aws ec2 describe-regions --all-regions  \
                             | jq -r '.Regions[] | "\(.RegionName)"')

    echo -n "Fetching images list from regions: "
    for r in $regions; do
        echo -n "$r "
        aws ec2 describe-images --owners 075585003325 \
                                 --profile "$profile" \
                                --region "$r"  \
            | jq -r '.Images[] | "\(.CreationDate),\(.ImageId),\(.Description),\(.BlockDeviceMappings[0].Ebs.SnapshotId) "' \
            | sort -t: -r -k1 > "region_$r.csv"
    done
    echo " - Done."
}
# --

function extract_old_amis() {
    local older_than_ts="$1"
    local region=""

    for region in region_*.csv; do
        local r="${region/#region_/}"
        echo "region,${r/\.csv/}"
        awk -F "," "\$1 < \"$older_than_ts\"" "$region"
        echo
    done
}
# --

function aws_unpublish_amis() {
    local aws"$1"
    local profile="$2"
    local ami_list="$3"
    local region=""

    while read -r line; do
        echo "$line" | grep -qE '^region,' && {
                                region=${line/*,/g}
                                continue; }
        local id=""
        id=$(echo "$line" | awk -F "," '{print $2}')
        [ -n "$id" ] && {
            $aws ec2 --region "$region" deregister-image --image-id "$id"
        }
    done <"$ami_list"
}
# --

function aws_delete_snapshots() {
    local aws"$1"
    local profile="$2"
    local ami_list="$3"
    local region=""

    while read -r line; do
        echo "$line" | grep -qE '^region,' && {
                                region=${line/*,/g}
                                continue
                            }
        local id=""
        id=$(echo "$line" | awk -F "," '{print $4}')
        [ -n "$id" ] && {
            $aws ec2 --region "$region" delete-snapshot --snapshot-id "$id"
        }
    done <"$ami_list"
}
# --

function print_help() {
echo
echo -n "Usage: $0 [--profile <aws-profile>] [--delete <ami list>]"
echo " [--unpublish <ami_list>] [--dry-run]"
echo -n "Retrieve AMI lists and generate list of old AMIs," 
echo " un-publish or delete AWS AMIs"
echo "         <aws-profile> AWS creds profile to use. Defaults to 'default'"
echo -n "         <ami-list> List of AMIs to unpublish / delete"
echo -n " EBS snapshots of. Generated by running $0 w/o "
echo " --delete or --unpublish option."
echo -n "         --dry-run (only for --delete/--unpublish)"
echo "p rints aws cli commands without executing them."
echo

}
# --
function aws_remove_old_amis() {
    local profile="default"
    local delete_file=""
    local unpublish_file=""
    local aws="aws"

    while [ 0 -lt $# ]; do
        case $1 in
            --profile)  profile="$2"; echo "Using profile $profile";
                        shift; shift;;
            --delete)   delete_file="$2"; shift; shift;;
            --unpublish)unpublish_file="$2"; shift; shift;;
            --dry-run)  aws=print_aws; shift;;
            --help)     print_help; return;; 
            *)          print_help; return;; 
         esac
    done

    local older_than=""
    older_than=$(date --date "$AWS_REMOVE_OLDER_THAN" +%Y-%m-%dT00:00:00.000Z)
    local result_file="amis_older_than_$older_than.csv"

    [ -f "$unpublish_file" ] && {
        echo "Un-publishing AMIs listed in $unpublish_file."
        aws_unpublish_amis "$aws" "$profile" "$unpublish_file"
    }

    [ -f "$delete_file" ] && {
        echo "Deleting all EBS snapshots listed in $delete_file."
        aws_delete_snapshots "$aws" "$profile" "$delete_file"
    }

    [ -f "$unpublish_file" ] || [ -f "$delete_file" ] && return

    aws_list_amis "$profile"
    extract_old_amis "$older_than" > "$result_file"
    echo "$result_file created"
}
# --


if [ "$(basename "$0")" = "aws-remove-old-amis.sh" ] ; then
	aws_remove_old_amis "$@"
fi
