#!/bin/bash

if [ $# -lt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage: $0 FLATCAR_VERSION_A FLATCAR_VERSION_B"
  echo "Shows the ebuild package changes between two Flatcar versions"
  echo "Environment variables:"
  echo "Set FROM_(A|B)=(release|bincache) to select an other image location than the bucket"
  echo "Set BOARD_(A|B)=arm64-usr to select an arm64 build"
  echo "Set CHANNEL_(A|B)=(alpha|beta|edge|developer) to select a build for another channel than stable"
  echo "Set FILE=(flatcar_production_image_contents.txt|flatcar_developer_container_packages.txt|flatcar_developer_container_contents.txt|flatcar_production_image_kernel_config.txt)"
  echo "  to show image contents or developer container packages instead of flatcar_production_image_packages.txt"
  echo "Set MODE_(A|B)=/developer/ to select a developer build"
  echo "Set FILESONLY=1 to reduce the flatcar_production_image_contents.txt file to contain only path information"
  echo "Set CUTKERNEL=1 to reduce the flatcar_production_image_contents.txt file to contain no kernel version in paths but just 'a.b.c-flatcar'"
  echo "Alternatively, set CALCSIZE=1 to sum up the file sizes from flatcar_production_image_contents.txt (/boot and /usr, excluding symlinks and directories)"
  exit 1
fi

set -euo pipefail

FROM_A="${FROM_A-bucket}"
FROM_B="${FROM_B-bucket}"
CHANNEL_A="${CHANNEL_A-stable}"
CHANNEL_B="${CHANNEL_B-stable}"
BOARD_A="${BOARD_A-amd64-usr}"
BOARD_B="${BOARD_B-amd64-usr}"
MODE_A="${MODE_A-/}"
MODE_B="${MODE_B-/}"
FILE="${FILE-flatcar_production_image_packages.txt}"
VERSION_A="$1"
VERSION_B="$2"
FILESONLY="${FILESONLY-0}"
CUTKERNEL="${CUTKERNEL-0}"
CALCSIZE="${CALCSIZE-0}"

A="$(mktemp "/tmp/$VERSION_A-XXXXXX")"
B="$(mktemp "/tmp/$VERSION_B-XXXXXX")"

trap "rm -f \"$A\" \"$B\"" EXIT

if [ "$FROM_A" = "release" ]; then
  URL_A="https://${CHANNEL_A}.release.flatcar-linux.net/${BOARD_A}/${VERSION_A}/${FILE}"
elif [ "$FROM_A" = "bincache" ]; then
  URL_A="https://bincache.flatcar-linux.net/images/${BOARD_A/-usr/}/${VERSION_A}/${FILE}"
else
  URL_A="https://bucket.release.flatcar-linux.net/flatcar-jenkins${MODE_A}${CHANNEL_A}/boards/${BOARD_A}/${VERSION_A}/${FILE}"
fi
if [ "$FROM_B" = "release" ]; then
  URL_B="https://${CHANNEL_B}.release.flatcar-linux.net/${BOARD_B}/${VERSION_B}/${FILE}"
elif [ "$FROM_B" = "bincache" ]; then
  URL_B="https://bincache.flatcar-linux.net/images/${BOARD_B/-usr/}/${VERSION_B}/${FILE}"
else
  URL_B="https://bucket.release.flatcar-linux.net/flatcar-jenkins${MODE_B}${CHANNEL_B}/boards/${BOARD_B}/${VERSION_B}/${FILE}"
fi

curl --location --silent -S -o "$A" "$URL_A"
curl --location --silent -S -o "$B" "$URL_B"

if [ "$FILE" = flatcar_production_image_contents.txt ] || [ "$FILE" = flatcar_developer_container_contents.txt ]; then
  # Cut date and time noise away
  sed -i 's/....-..-.. ..:.. //g' "$A" "$B"
  # Sort by path
  sort -t / -k 2 --output "$A" "$A"
  sort -t / -k 2 --output "$B" "$B"
  if [ "$FILESONLY" = 1 ]; then
    cut -d . -f 2- "$A" > "$A.cut"
    mv "$A.cut" "$A"
    cut -d . -f 2- "$B" > "$B.cut"
    mv "$B.cut" "$B"
  fi
  if [ "$CUTKERNEL" = 1 ]; then
    sed -i -E 's#[0-9]+\.[0-9]+\.[0-9]+-flatcar#a.b.c-flatcar#g' "$A" "$B"
  fi
  if [ "$CALCSIZE" = 1 ]; then
    A_SUM=$(($(grep -v '^d' "$A" | grep -v '^l' | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    A_BOOT=$(($(grep -v '^d' "$A" | grep -v '^l' | grep " [\.]*/boot" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    A_USR=$(($(grep -v '^d' "$A" | grep -v '^l' | grep " [\.]*/usr" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    A_ROOT=$(($(grep -v '^d' "$A" | grep -v '^l' | grep -v " [\.]*/usr" | grep -v " [\.]*/boot" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    echo "Sum: $((${A_SUM}/1024/1024)) MiB" > "$A"
    echo "Boot: $((${A_BOOT}/1024/1024)) MiB (must be < 60 MiB or updates will break)" >> "$A"
    echo "Usr: $((${A_USR}/1024/1024)) MiB (inc. sparse files/hardlinks)" >> "$A"
    echo "Rootfs: $((${A_ROOT}/1024/1024)) MiB" >> "$A"
    B_SUM=$(($(grep -v '^d' "$B" | grep -v '^l' | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    B_BOOT=$(($(grep -v '^d' "$B" | grep -v '^l' | grep " [\.]*/boot" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    B_USR=$(($(grep -v '^d' "$B" | grep -v '^l' | grep " [\.]*/usr" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    B_ROOT=$(($(grep -v '^d' "$B" | grep -v '^l' | grep -v " [\.]*/usr" | grep -v " [\.]*/boot" | tr -c '[:graph:][:space:]' '?' | rev | cut -d ' ' -f 2 | rev | paste -sd+ -)))
    echo "Sum: $((${B_SUM}/1024/1024)) MiB" > "$B"
    echo "Boot: $((${B_BOOT}/1024/1024)) MiB (must be < 60 MiB or updates will break)" >> "$B"
    echo "Usr: $((${B_USR}/1024/1024)) MiB (inc. sparse files/hardlinks)" >> "$B"
    echo "Rootfs: $((${B_ROOT}/1024/1024)) MiB" >> "$B"
  fi
fi

git diff "$A" "$B"
