#!/bin/bash

if [ $# -lt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage: $0 FLATCAR_VERSION_A FLATCAR_VERSION_B"
  echo "Shows the ebuild package changes between two Flatcar versions"
  echo "Environment variables:"
  echo "Set BOARD_(A|B)=arm64-usr to select an arm64 build"
  echo "Set CHANNEL_(A|B)=(alpha|beta|edge|developer) to select a build for another channel than stable"
  echo "Set FILE=(flatcar_production_image_contents.txt|flatcar_developer_container_packages.txt|flatcar_developer_container_contents.txt)"
  echo "  to show image contents or developer container packages instead of flatcar_production_image_packages.txt"
  echo "Set MODE_(A|B)=/developer/ to select a developer build"
  echo "Set FILESONLY=1 to reduce the flatcar_production_image_contents.txt file to contain only path information"
  echo "Set CUTKERNEL=1 to reduce the flatcar_production_image_contents.txt file to contain no kernel version in paths but just 'a.b.c-flatcar'"
  echo "Alternatively, set CALCSIZE=1 to sum up the file sizes from flatcar_production_image_contents.txt (/boot and /usr, excluding symlinks and directories)"
  exit 1
fi

set -euo pipefail

CHANNEL_A="${CHANNEL_A-stable}"
CHANNEL_B="${CHANNEL_B-stable}"
BOARD_A="${BOARD_A-amd64-usr}"
BOARD_B="${BOARD_B-amd64-usr}"
MODE_A="${MODE_A-/}"
MODE_B="${MODE_B-/}"
FILE="${FILE-flatcar_production_image_packages.txt}"
VERSION_A="$1"
VERSION_B="$2"
FILESONLY="${FILESONLY-0}"
CUTKERNEL="${CUTKERNEL-0}"
CALCSIZE="${CALCSIZE-0}"

A="$(mktemp "/tmp/$VERSION_A-XXXXXX")"
B="$(mktemp "/tmp/$VERSION_B-XXXXXX")"

trap "rm -f \"$A\" \"$B\"" EXIT

curl --location --silent -S -o "$A" https://bucket.release.flatcar-linux.net/flatcar-jenkins"$MODE_A""$CHANNEL_A"/boards/"$BOARD_A"/"$VERSION_A"/"$FILE"
curl --location --silent -S -o "$B" https://bucket.release.flatcar-linux.net/flatcar-jenkins"$MODE_B""$CHANNEL_B"/boards/"$BOARD_B"/"$VERSION_B"/"$FILE"

if [ "$FILE" = flatcar_production_image_contents.txt ] || [ "$FILE" = flatcar_developer_container_contents.txt ]; then
  # Cut date and time noise away
  sed -i 's/....-..-.. ..:.. //g' "$A" "$B"
  # Sort by path
  sort -t / -k 2 --output "$A" "$A"
  sort -t / -k 2 --output "$B" "$B"
  if [ "$FILESONLY" = 1 ]; then
    cut -d . -f 2- "$A" > "$A.cut"
    mv "$A.cut" "$A"
    cut -d . -f 2- "$B" > "$B.cut"
    mv "$B.cut" "$B"
  fi
  if [ "$CUTKERNEL" = 1 ]; then
    sed -i -E 's#[0-9]+\.[0-9]+\.[0-9]+-flatcar#a.b.c-flatcar#g' "$A" "$B"
  fi
  if [ "$CALCSIZE" = 1 ]; then
    A_SUM=$(grep -v '^d' "$A" | grep -v '^l' | rev | cut -d ' ' -f 2 | rev | paste -sd+ - | bc)
    echo "$(echo "${A_SUM}/1024/1024" | bc) MiB" > "$A"
    B_SUM=$(grep -v '^d' "$B" | grep -v '^l' | rev | cut -d ' ' -f 2 | rev | paste -sd+ - | bc)
    echo "$(echo "${B_SUM}/1024/1024" | bc) MiB" > "$B"
  fi
fi

git diff "$A" "$B"
