#!/bin/bash

# Synchronizes all the branches from the CoreOS upstream to the flatcar-linux
# organization clones.

set -e

REPOS=(
  "baselayout"
  "bootengine"
  "chromite"
  "coreos-cloudinit"
  "afterburn"
  "coreos-overlay"
  "dev-util"
  "docker"
  "efunctions"
  "etcd"
  "etcdctl"
  "fero"
  "grub"
  "ignition"
  "init"
  "locksmith"
  "mantle"
  "mayday"
  "nss-altfiles"
  "portage-stable"
  "rkt"
  "scripts"
  "sdnotify-proxy"
  "seismograph"
  "shim"
  "sysroot-wrappers"
  "systemd"
  "toolbox"
  "torcx"
  "update-ssh-keys"
  "update_engine"
  "updateservicectl"
)

REPOS_MANIFEST=(
  "manifest"
  "manifest-builds"
)

# update-branches gets all the upstream branches, checks them out and pushes to
# the origin.
#
# It assumes upstream and origin remotes are created and up to date.
function update-branches() {
  local UPSTREAM="${1}"
  local ORIGIN="${2}"
  local PUSH_TAGS="${3}"
  local UPSTREAM_BRANCHES

  UPSTREAM_BRANCHES=$(git branch -r | grep "^[ ]*$UPSTREAM" | grep -v HEAD | cut -d/ -f 2-)

  for branch in ${UPSTREAM_BRANCHES}; do
    git checkout -B "${branch}" "${UPSTREAM}/${branch}"
  done

  # use the --force, Luke!
  git push --all --force "${ORIGIN}"

  # push tags only if PUSH_TAGS is true
  if [[ ${PUSH_TAGS} == "1" ]] ; then
    git push --tags "${ORIGIN}"
  fi
}

# Merge each upstream systemd branch to Flatcar branch, e.g. v241-coreos to v241-flatcar.
# We need to deal with the special case, because of the special case of systemd repo,
# which has no base point like "flatcar-master" branch. So if upstream has updated
# the v241-coreos branch, that change needs to be also applied to v241-flatcar.
function update-systemd-branches() {
  local UPSTREAM="${1}"
  local ORIGIN="${2}"
  local UPSTREAM_BRANCHES

  UPSTREAM_BRANCHES=$(git branch -r | grep "^[ ]*$UPSTREAM/v2[4-9][1-9]" | grep -v HEAD | cut -d/ -f 2-)

  for upstream_branch in ${UPSTREAM_BRANCHES}; do
    local flatcar_branch
    flatcar_branch="${upstream_branch//-coreos/-flatcar}"

    git checkout -B "${flatcar_branch}" "${ORIGIN}/${flatcar_branch}"
    git merge "${UPSTREAM}/${upstream_branch}"
    git push "${ORIGIN}" "${flatcar_branch}"
  done
}

if [ $# -eq 1 -a -d "${PWD}/$1" ] ; then
    PREFIX="$1"
    echo "Using existing directory $PREFIX"
    # we're not cleaning up this one since it's user provided
else
    PREFIX=$(mktemp -d "${PWD}/.update-repos.XXXXXXXXXX")
    echo "Created new directory $PREFIX"
    # clean up
    trap '{ export EXT="$?"; rm -rf "${PREFIX}" && exit "${EXT}"; }' EXIT
fi

cd "${PREFIX}"


for repo in "${REPOS[@]}"; do
  [ ! -d "${repo}" ] && git clone "git@github.com:flatcar-linux/${repo}"

  pushd "${repo}"
  git remote add upstream "https://github.com/coreos/${repo}" || true
  git fetch --all
  update-branches upstream origin 1

  if [ "${repo}" = "systemd" ]; then
    update-systemd-branches upstream origin
  fi

  popd
done

for repo in "${REPOS_MANIFEST[@]}"; do
  [ ! -d "${repo}" ] && git clone "git@github.com:flatcar-linux/${repo}"

  pushd "${repo}"
  git remote add upstream "https://github.com/coreos/${repo}" || true
  git fetch --all
  update-branches upstream origin 0

  popd
done
